baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Connor Kirkpatrick"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-107230293-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ConnorKirk"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ConnorKP"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/connorkirkpatrick/"

[params]
    description = "Connor Kirkpatricks personal site for Squash, R, data and thoughts"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

