[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

# Force HTTPS

Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[build.environment]
HUGO_VERSION = "0.80.0"
