---
title: Best of three games - Is new always better?
author: Connor Kirkpatrick
date: '2017-07-17'
slug: best-of-three-games-is-new-always-better
categories:
  - Squash
tags: []
draft: TRUE
---

# Introduction

* Situation
* What am I discussing

Currently there is an ongoing debate in the professional squash community. At the world championships in Dubai, the format of the matches was changed, from Best of 5 games to just Best of 3. The response to this has been fascinating, with well thought out arguments from a number of professional players and coaches.

Following the tournement, Malcom Willstrop, coach and father to James Willstrop wrote an article suggesting it was time to move to best of 3 in professional tournments (the lifeblood of the professional squash). Many players quickly  declared for a particular camp, with many writing arguments to support their case.

# Body
* Explanation
* Interesting arguments

# What do the professional's say?

Nick Matthew has written a very good argument based on this. He argues that Best of 3 style tournements could be mixed in with Best of 5, similar to cricket with it's 20/20 and 5 day internationals.

Others have outright declared Best of 3 the future of squash, adding that it's evolve or die. This is contested by others who argue that a move to best of 3 would reduce the value of endurance and fitness of a sport famed for this.


# What is the difference?

At it's core, the best of 3 format is not just a truncated best of 5. A player would likely be stronger at one format than the other, depending on their play style. Perhaps this has coloured player's opinion on the proposed change?

Best of 3 increases the importance of every point. There's far less room to wriggle. 
* Urgency
* Less leeway
* Matches will be a maximum of 3 games, rather than a minimum of 3. Knowing this, the game shifts from  valuing the fitness/endurance. Knowing you have only 1 spare game (11 points), you don't have much leeway. It's argued that this raises the intensity, aggression and excitement of the match.

I think that the best of three format has a very different profile (flavour?) to best of 5, akin to the change from English to American style scoring, (and to a lesser extent the move from 15 point games to 11).

* Less intense tournement paths. Squash tournements are quite condensed affairs. A 5 game match early in a tournement will probably still be hurting by the time you next play. Reducing the games to 3 will allow players to be in a better state for the finals. It may reduce their risk of injury?

* Would match length be affected? 

To win a best of 5 game, you need to win 3 matches. In each match, you need to be the first to 11 points (excluding 2-clear at 10-10). In best of three, this reduces to just 2 games, and 22 points. At first glance it seems obvious that matches will be shorter. Is this a desired consequence?



# Conclusion
