---
title: How to measure productivity?
author: Connor Kirkpatrick
date: '2017-06-12'
slug: how-to-measure-productivity
categories: []
tags: []
draft: TRUE
---


Recently, I was asked "How should we measure productivity?" within the context of a customer services team. Here are the thoughts I put together.


# How do we define productivity?

Productivity is defined as the rate of input to desired output.

This definition is rather abstract though. Context is everything. So how should we measure productivity in a customer operations team?

The core function of the customer operations team is to respond to inbound customer requests. Successful customer service would involve:
* Respond to majority of inbound engagements from customers
* Solving the query in a high quality resolution (not all answers are equal).
* Time to solve a query?
* Time to respond to a query - Could this be part of the above?


These could all be considered in a measure of productivity. 

Let's start with a simple measure. We could measure productivity as the number of customer operations team required to respond to these engagements in a fixed time period.. ie 

`Productivity = Number of Customer Engagements resolved in one day / Number of Customer Operations Team Members`


But this ignores some other factors. If we put weight with purely the number of engagements served by a team, we ignore a big factor - Quality. This is harder to quantify (which explains the number of overseas call centres). Not all customer services are equal. 

Our current definition is naive. In fact, optimising for our measure could damage, not improve our goal, as we would modify behaviour and processes to improve throughput whilst not tracking for quality. If the customer services team knew they were purely judged on the number of customers queries engaged with, then they prioritise that ahead of other factors.

# Other Factors to consider

As we've discussed above, we there's more to consider for whilst measuring productivity.

## Quality

### It's not what you say, but how you say it

Two customers phone a helpdesk with the same problem. They both get their query resolved in a timely manner, yet one now has an improved opinion of the company, the other a worse opinion. The difference can be down to the team member they spoke to. One was patient, kind and clear, the other brisk, strained and opaque.

### How do you track a feeling?

It's tricky to track quality of customer service. You could try to measure it directly with tools such as sentiment analysis of what's being said (and the tone), but this is still unreliable (and a bit creepy).
An easier way is to ask the customer! Either directly, with surveys, questions and the like, or indirectly. You could do this be seeing if they then post positive or negative things regarding the engagement, or by monitoring their activity on the company service. 

### How does this relate to productivity again?

- Customer Satisfaction needs to be considered in a productivity measure
- Either as binary (Customer satsifcation > Target)
- Or sliding scale 



## Number of Inbound Engagements

- Example: Team of 10 customer service reps able to handle 1000 customer engagements per day.
  But, the inbound number of queries is actually 1100. Should we track this in productivity?
  
- Argument For
  
- Argument Against
  Well, if we know that we can handle 1000 engagements with 10 people, we would know we need 2 more people to cover capacity (plus some extra).





# Is maximum productivity producitive?

To finish this discussion, I wanted to discuss the unquantifiable part of customer service. The human interaction, the feeling you have after a great conversation. Whilst this is difficult to measure, it shouldn't be ignored. If you're customer service team can handle 1,000 customer service engagements a day, would you want it to be at capacity all the time?

A lower utilisation would allow the customer services team to shine.

# A final thought

As with everything, these measurements don't exist in an abstract space. Speaking to the Customer Operations team would be a wise step before I prescribed a good measure for productivity. We should test our measure to see if it is meaningful.


