---
title: My Morning Routine
author: Connor Kirkpatrick
date: '2017-07-29'
slug: my-morning-routine
categories: []
tags: []
---

# A Morning Routine

Whilst listening to my usual parade of podcasts last week, I came across one discussing morning routines of "successful people".  I didn't fully buy in to some of the routines, but  the idea of consciously deciding how to start every day did appeal. Creating a habit of a certain morning routine could help start each day well, increasing my likelihood of being productive that morning and hopefully following on into the rest of the day. Additionally, it may be a good opportunity to make small regular gains in a skill or activity, which like compound interest, can lead to large gains over time.


## My Current Routine

When I reflected on my current routine, I realised that it was quite variable. I consistently woke up around 7am, but that's about it. Beyong that, my next actions varied depending on if I was at home or in a hotel.

At a hotel, I usually wake up, then immediately shower. After that I'll settle down to address any non work tasks I want to do. I usually intend to do learning or coding at this time, but don't always succeed.

At home, I generally go to the gym immediately after waking up. It's a pleasant way to start the day, but not always possible. After that, it's a quick shower and on with my day.


## What to consider in a new routine?

When considering what my *conscious* routine should look like, I decided it aim for the following:

* Brief
* Simple
* Repeatable


These three things are all interlinked. The biggest challenge of intentionally setting myself a routine is making sure I stick to it. My enemies in this are a lack of time, not having the resources, and lack of willpower. Keeping it simple to start with should help with this. Once it's consistent, I could look to achieve more.

## What to include in a routine?

The goal of having a routine is to:

* Ensure I'm productive
* Make regular small progress in a chosen area.


With that in mind, some possible items could be

* Practice my squash swing
* Stretching
* Read on a topic I'm trying to understand
* Writing/Journaling

None of these fit into a perfect routine. My girlfriend won't appreciate me swinging my squash racket around whilst she's asleep. Reading a topic, especially if it's dry, may send me back to sleep!

In my first attempt at a routine, I've decided to go a bit higher level. It looks like this

1. Wake up (of course...)
1. ~ 5 Minutes of something physical. Either stretching or grooving my squash swing
1. ~ 5 minutes of something mental. Either journaling or writing a blog post
1. Shower!

After that, I should be ready to start my day.

I have concerns that after my shower I can often get distracted. Perhaps having a task following it would help lead me into the next productive activity?

