---
title: Food vs "Food"
author: Connor Kirkpatrick
date: '2017-06-15'
slug: food-vs-food
categories: []
tags: []
---


Plan 

Intro

about me
what is this
what made me think of this

Main Body
discussion
both sides
compromise

Conclusion


The majority of the food I eat (and enjoy), I wouldn't have considered 5 years ago. In that time, my diet has changed significantly. I attribute the majority of this change to living with my girlfriend, who expanded my horizens. Without her, I never would have discovered the wonder of Aubergine. (Or maybe I would have, but we will never know).

My attitude to food in that time has changed significantly as well. This post is an attempt to clarify the thoughts that have been developing recently.

At university 7 years ago, my staple foods were Chicken Curry, Sausage Pasta, Chicken Fajitas and Peanut Butter. These were coincidentally the foods I knew how to cook. You could template every meal as either rice/pasta with sauce or potato based, meat and a vegetable.

The change between myself now and then has been the changing of this template. Now, a standard meal for me would be

* Green Vegeatable (Cavalo Nero, Brocolli, Spinach, Salad)
* Meat (Chicken, Sausage).

The potato staple of my diet has been replaced with green veg. 

As well as the template of my diet, my attitude with food has also changed. Food has almost become two seperate ideas for me, which I try to compromise between.

### Food

"The key ingredients of cooking. Building blocks of delicious meals. Something that can bring joy"

### "Food"

"The nutrition needed to fuel the body. The ingredients in will directly affect performance, visuals and feel of my body"."

Every meal now can sometimes feel like a choice between the two types of food. "Food" for performance is growing in importance for me as I improve at Squash and Running. Having done a month of vegetarianism, and a month of Low Carb - High Fat, I've been to notice the real impact that food has on my mood and energy. 

It seems that food can give me both short and long term happiness, but the foods types that give each don't neccessarily intersect.

THis seems quite negative, but actually I have begun to enjoy what I consider "performance food" and at the same time have completely lost interest in other food. Icecream, Crisps, Sugary drinks all now are too sweet to enjoy. I think this was an unintentional benefit of my low-carb month. After avoiding sugary items for so long, my perception of sweetness seems to have increased.