---
title: Thinking about thinking
author: Connor Kirkpatrick
date: '2017-06-19'
slug: thinking-about-thinking
categories: []
tags: []
draft: TRUE
---

Recently I have been trying to lose weight. There are a few reasons why, partly image, partly for health and fitness. The main reason though, is to see if I can. It's not something that comes naturally to me, so to be strict about my diet for a consistent period of time is a challenge. I'd like to be able to master that challenge.

But this isn't about that.

As I'm trying to lose weight at the moment, it's on my mind a lot. Last night I came to the conclusion that all this extra time in my mind wasn't helping. I can only lose weight by eating less, not by thinking about it. In fact thinking about the food I'm not eating, and if I'm making progress only makes it worse.

So what should I think about instead? Is there something I should consciouslly choose to occupy my mind when it's unfocused?

Some possible idea's I've had

* Mindfulness - Thinking about nothing
* Appreciation - What's going well today
* Goals
* Planning my days


