---
title: Mindful Eating
author: Connor Kirkpatrick
date: '2017-09-13'
slug: mindful-eating
categories: []
tags: []
draft: True
---

# Mindful Eating

After a few years of eating wit my girlfriend, my basic diet is quite good. I enjoy salads, a wide variety of fish and vegetables and the rest. I even now finding myself uninterested in food when I'm full, and choosing "healthier" options because I think they taste better. I'm really pleased with this. It's a large change from when I was younger!

But in my long walk towards for self-improvement, I've noticed that I still have one unhealthy tendancy. I often binge eat, especially sweet foods like biscuits, cookies and other baked goods. It's become very binary, in that I can either eat none, and I will be fine. But if I have one, I'll have two. Then a third. Suddenly the entire packet is empty. This isn't ideal. It's definitely worse than eating an entire bag of carrots!

So what to do?

There's a few things at play

* Ability to stop after "just one". Should I try to build a pattern of eating just one?
* Being mindful when I'm eating. It's often convenience foods, that I can eat whilst doing something else. If I were to only eat these foods when doing nothing else, perhaps I would be less likely to eat it all!
* Avoid purchasing food that I will likely binge eat
  * Peanut butter
  * Cookies
  * Brownies
  * Biscuits
  * Chocolate