---
title: Food Report - Homemade Burgers
author: Connor Kirkpatrick
date: '2017-07-17'
slug: food-report-homemade-burgers
categories: []
tags: []
---
#Burgers

For the past few months I've been slacking. Burger nights have become a common weekend dinner. Peanut butter, fried onions, mayoniaise, sweet chilli sauce are all regularly featured.

Every time though, I've taken the path of least resistance and bought pre-made burgers. Despite my best efforts, they've always tasted better than my own attempts. Better texture, better flavour (and also easier).

Recently though, I came across the burger section  "The Food Lab" by J. Kenji Lopez. It's inspired me to try again at burger mastery. I'm pleased to say this weekend I came a step closer.

## What worked?

* Freshly ground beef from the Farmers Market. This was an instant winner, with a much better texture and taste than store bought.

* Patties made from only ground beef. No onions, seasoning or any other distractions.

* Only season the outside of the patty.
 
* Freshly made sourdough bun from the Farmers Market. This managed to hold it's integrity despite the juices.

* Toasting the buns with butter in a pan. This created a lovely crisp texture and golden colour.

* Resting the burgers after cooking


## What could be better?

* I still managed to overcook the burger! Next time I need to be more strict with measuring the internal temperature.

* At 200g, the burgers were a quite large for my preference. Next time I will try smaller ~120g patties.

* Toppings. Maybe I just missed peanut butter (thanks diet), but it seemed a little bland. Next time I'd like to plan a more cohesive topping selection ahead of time, rather than making it up on the spot.

* Photo's! I should take some photos of the steps and results.
